"""gui/interfaces.py — MVP 介面定義（typing.Protocol）

所有 QWidget 相關模組不得在此 import。
Presenter 與 View 透過本模組的 Protocol 互相解耦。
"""
from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class IMainView(Protocol):
    """View 暴露給 Presenter 的最小介面。"""

    def show_error(self, title: str, msg: str) -> None:
        """以彈窗顯示錯誤訊息。"""
        ...

    def set_status(self, text: str) -> None:
        """更新底部狀態列文字。"""
        ...

    def refresh_view(self) -> None:
        """重新整理縮圖清單（model.refresh_all）。"""
        ...

    def get_selected_rows(self) -> list[int]:
        """回傳目前已選取的行索引（升序）。"""
        ...


@runtime_checkable
class IMainPresenter(Protocol):
    """Presenter 暴露給 View 的最小介面（供 Signal 連接）。"""

    def on_add_pdf(self) -> None: ...
    def on_add_folder(self) -> None: ...
    def on_rotate_pages(self, angle: int) -> None: ...
    def on_delete_pages(self) -> None: ...
    def on_export_pdf(self) -> None: ...
    def on_export_selected_pdf(self) -> None: ...
    def on_pages_reordered(self, source_rows: list[int], target: int) -> None: ...
    def load_pdfs(self, files: list[str]) -> None: ...
    def undo(self) -> None: ...
    def redo(self) -> None: ...
